name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: tha-guy-nate/tha-github-workflows/.github/workflows/python-publish.yml@main
